server:
  port: 8080
  servlet:
    context-path: /

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/jspdb?serverTimezone=Asia/Seoul
    username: jspbook
    password: passwd

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    #show-sql: true
    properties:
      hibernate.format_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false

  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

cos:
  key: cos1234

  # model 프로퍼티 camel case 설정
  mybatis.configuration.map-underscore-to-camel-case=true

  # xml파일 result type에 패키지명을 생략할 수 있도록 alias 설정
  mybatis.type-aliases-package=com.example.mappertut.model

  # Mybatis mapper 위치 설정
  mybatis.mapper-locations= mapper/*.xml